### ISSUE TITLE
Add ClientBuilder

### ISSUE THREAD

**Issue by letmutx** [aisk/rust-memcache#107]
After #104 lands, we should expose more options to configure the connection pool. I intentionally left this out to keep the PR small for review.

In addition to the pool options, we should also add support for setting a custom hash function without having to do `client.hash_function = ...`.

**Comment by Shahab96** [comment]
This seems to have been here a while, I do think it's worth doing for me, as I'd like to contribute to this project. Mind if I nab this and go off the PR @letmutx submitted previously?

**Comment by aisk** [comment]
Hi @Shahab96, since this is an open source project, you wouldn't need to ask before contributing. But since I don't have enough time for this project these days, if you want to make a contribution, I would very much appreciate it if you could make the PR smaller as possible, like splitting one large PR into small PRs.

**Comment by Shahab96** [comment]
resolved by #141
